#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Fri May 20 21:15:35 2022
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from .MainFrame import MainFrame


class AppWindmin(wx.App):
    def OnInit(self):
        self.frameMain = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frameMain)
        self.frameMain.Show()
        return True

# end of class AppWindmin
